Task 2
arthur100500/formal-lang-course pull request #2
Opened 2023-09-17 23:54 UTC by arthur100500

2023-09-21 20:37 UTC, rustam-azimov requested changes

2023-09-21 20:37 UTC, rustam-azimov commented on project/automaton_lib.py
> +    return regex.to_epsilon_nfa().to_deterministic().minimize()
Есть лишний вызов тут

2023-09-21 20:37 UTC, rustam-azimov commented on project/automaton_lib.py
> +    automaton = NondeterministicFiniteAutomaton.from_networkx(graph)
Проверьте не может ли получится enfa

2023-09-21 20:37 UTC, rustam-azimov commented on project/automaton_lib.py
> +    if starting_nodes is not None:
Будут ли все стартовыми и финальными если оба None?

2023-09-21 21:57 UTC, arthur100500 commented on project/automaton_lib.py
> +    return regex.to_epsilon_nfa().to_deterministic().minimize()
Убрал `to_deterministic`

2023-09-21 21:57 UTC, arthur100500 commented on project/automaton_lib.py
> +    automaton = NondeterministicFiniteAutomaton.from_networkx(graph)
Убрал ε переходы с помощью `remove_epsilon_transitions`

2023-09-21 21:57 UTC, arthur100500 commented on project/automaton_lib.py
> +    if starting_nodes is not None:
Почему-то подумал что надо использовать те что в графе, теперь поменял на все при None

2023-09-22 14:42 UTC, rustam-azimov approved these changes

2023-09-22 15:25 UTC, merged