Task 3
arthur100500/formal-lang-course pull request #3
Opened 2023-09-25 20:33 UTC by arthur100500

2023-09-27 17:12 UTC, rustam-azimov requested changes

2023-09-27 17:12 UTC, rustam-azimov commented on project/automaton_lib.py
> +def regular_request(
Лучше переименовать на regular_path_query или rpq

2023-09-27 17:12 UTC, rustam-azimov commented on project/automaton_lib.py
> +    graph: nx.MultiDiGraph, start_nodes: List[str], final_nodes: List[str], regex: Regex
Возможно также пригодится учесть вариант, когда стартовые или конечные не даны (выбрать все тогда).

2023-09-27 17:13 UTC, rustam-azimov commented on project/automaton_lib.py
> +    graph: nx.MultiDiGraph, start_nodes: List[str], final_nodes: List[str], regex: Regex
И может лучше множества использовать, а не списки?

2023-09-27 19:19 UTC, arthur100500 commented on project/automaton_lib.py
> +    graph: nx.MultiDiGraph, start_nodes: List[str], final_nodes: List[str], regex: Regex
Оно было учтено, так как дергается функция `nfa_of_graph`, где оно так и работает, только не помечено в аннотации и докстринге было. Теперь добавил и заменил на Set

2023-09-27 19:20 UTC, arthur100500 commented on project/automaton_lib.py
> +def regular_request(
Переименовал на `regular_path_query`

2023-09-28 14:54 UTC, rustam-azimov approved these changes

2023-09-28 14:59 UTC, merged