Task 4
arthur100500/formal-lang-course pull request #4
Opened 2023-10-04 16:09 UTC by arthur100500

2023-10-05 07:03 UTC, rustam-azimov requested changes

2023-10-05 07:03 UTC, rustam-azimov commented on project/automaton_lib.py
> +    start_nodes: List[str],
Также нужно задавать множество финальных вершин. И если не указано, то все стартовыми и финальными делаем.

2023-10-05 10:47 UTC, arthur100500 commented on project/automaton_lib.py
> +    start_nodes: List[str],
Добавил `get_reachable_final_nodes_constrained`, там можно задать теперь стартовые и финальные вершины, и добавил тесты на корректную работу

2023-10-08 07:07 UTC, rustam-azimov approved these changes

2023-10-23 13:02 UTC, merged